### ISSUE TITLE
Vite HMR / auto reload is broken.

### ISSUE THREAD

**Issue by pfinkbeiner** [jepiqueau/vite-vue-sqlite-app#2] opened 2023-02-27 12:58 UTC
### How to Reproduce 

Tested on M1 Pro (if relavant)

1. git clone …
2. npm run ci (to ensure versions are exactly the same)
3. npm run dev
4. Change any file to trigger auto reload.

<img width="723" alt="image" src="https://user-images.githubusercontent.com/722890/221569198-3e0b422d-4ba1-4533-89de-103415186f5a.png">

At first, everything works like expected. After we change something we see an error like in the screenshot above. 
I tried to use the SQLlite plugin myself and had the same issue. Manual reload of page and the error is gone. Any Idea whats causing this?

**Comment by jepiqueau** [comment] 2023-02-28 12:35
@pfinkbeiner thanks for reporting this. Difficult to reproduce it is happening once and if i do a second modification it is working well.and if i reloaded manually it is working fine. I will come back when i found a fix

**Comment by jepiqueau** [comment] 2023-03-01 07:19
@pfinkbeiner i have modified the vite.config.ts  file can you try again, with this modification i could not reproduce the issue. Thanks to revert to me.

**Comment by jepiqueau** [comment] 2023-03-11 07:38
@pfinkbeiner as you did not answer i assume that is fixed so i close the issue

**Closed as completed by jepiqueau** 2023-03-11 07:38 UTC
